spring:
  datasource:
    url: jdbc:mysql://localhost:3306/awdb?useSSL=false&serverTimezone=UTC
    username: appUser
    password: app123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false